### ISSUE TITLE
Tracker error message tweaks

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#241]
Currently:
![image](https://cloud.githubusercontent.com/assets/2693690/22850312/3581bbe4-efbc-11e6-8f66-7c926c1fe85b.png)

- [x] Error message should be the full width of the panel
- [x] Errors should not be dismissible. It's an unnecessary distraction.
- [x] Error should not have a bullet point if there's only one error
- [x] Relevant field should have a red border (e.g. https://getbootstrap.com/css/#forms-control-validation)
- [x] In this particular error (not entering anything and hitting search), can we change the message to "Please enter an ID number"?  Also, can we clarify the number? Is it "application ID number", or "permit ID number" or something else?

**Comment by racheledelman** [comment]
Also, this is the only error message that appears outside the card. Is there a reason for this?

![image](https://cloud.githubusercontent.com/assets/2693690/22850387/50e9d35c-efbd-11e6-9039-e55f34954746.png)
